#
# Preprocess the HMEC data set
#

source("common.R")

# list of HMEC peaks IDs passing QC
qc_list_path <- file.path(input_data_path, "qc-peak-ids.tsv")
peak_qc_list <- read.table(
    qc_list_path,
    sep = "\t", header = TRUE
) %>% filter(qc == 1) %>% select(peak_id)

# Read peak list generated by NetID
peak_list_path <- file.path(input_data_path, "nodelist-netid-pos-neg.csv")
hmec_peak_list <- read.delim(
    peak_list_path,
    sep = ",", header = TRUE
)

# use row numbers as peak IDs
hmec_peak_list <- hmec_peak_list %>% mutate(peak_id = row_number())
# subset to QC peaks only
hmec_peak_list <- hmec_peak_list %>%
    inner_join(peak_qc_list, by = join_by(peak_id))
# drop unused fields and recover m/z from mass
hmec_peak_list <- hmec_peak_list %>%
    select(peak_id, mass, path, ion_mode) %>%
    rename(netid_annotation = path) %>%
    mutate(mz = mass + proton_mass*ion_mode)

# write QC peak list (721 peaks)
write.table(
    hmec_peak_list,
    file.path(preprocessed_data_path, "qc-peak-list.tsv"),
    sep = "\t", row.names = FALSE, quote = FALSE
)

# read peak areas
peak_areas_path <- file.path(input_data_path, "hmec-peak-areas.tsv")
hmec_peak_areas <- read.table(
    peak_areas_path,
    sep = "\t", header = TRUE
)
# order tracer data columns alphabetic by tracer, unlabeled data last
tracer_data_col_names = colnames(hmec_peak_areas)[3:65]
column_order <- c(1:2, 2 + order(tracer_data_col_names), 66:68)

# subset to QC peaks
hmec_peak_areas <- hmec_peak_areas[
    which(hmec_peak_areas$peak_id %in% hmec_peak_list$peak_id),
    column_order
]

# write QC peak areas
write.table(
    hmec_peak_areas,
    file.path(preprocessed_data_path, "qc-peak-areas.tsv"),
    sep = "\t", row.names = FALSE, quote = FALSE
)

