#
#  Some functions commonly used in these scripts
#
# NOTE: Some of these could be moved to the remn package
#

# convolute MID matrices column by column
convolute_all <- function(mids_1, mids_2)
{
    sapply(
        1:ncol(mids_1),
        function(i) convolute(mids_1[, i], mids_2[, i])
    )
}

# write matrix as PNG image (for Illustrator) after applying a color function
# such as those generated by colorRamp()
# rows of the matrix are laid out from top to bottom.
write_image <- function(file_path, mat, color_fn)
{
    png::writePNG(
        aperm(
            apply(mat, c(1,2), color_fn) / 255,
            c(2,3,1)
        ),
        file_path
    )
}

reverse_rows <- function(mat)
{
    return(mat[nrow(mat):1, ])
}